[theme]
primaryColor = "#2196F3"
backgroundColor = "#121212"
secondaryBackgroundColor = "#1E1E1E"
textColor = "#FFFFFF"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8501
maxUploadSize = 200

[browser]
gatherUsageStats = false
